(function(){
const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
const PDF_URL='assets/boletines/Boletin_Judicial_PJCDMX_2022-03-31.pdf';
let lastResults=[];
function norm(s){return (s||'').toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/\s+/g,' ').trim();}
function escCsv(v){v=(v||'').toString().replace(/\r?\n/g,' '); return '"'+v.replace(/"/g,'""')+'"';}
function requireSession(){if(document.body.dataset.protected==='true' && sessionStorage.getItem('cj_session')!=='ok') location.href='index.html';}
function setupLogin(){const f=$('#loginForm'); if(!f) return; f.addEventListener('submit',e=>{e.preventDefault(); const u=$('#username').value.trim(); const p=$('#password').value; if(u==='admin'&&p==='admin'){sessionStorage.setItem('cj_session','ok'); location.href='home.html'} else $('#loginMsg').textContent='Credenciales demo incorrectas.';});}
function setupLogout(){ $$('[data-logout]').forEach(b=>b.addEventListener('click',()=>{sessionStorage.removeItem('cj_session'); location.href='index.html';}));}
function data(){return window.BOLETIN_INDEX||[];}
function populateSections(){const sel=$('#sectionFilter'); if(!sel) return; const sections=[...new Set(data().map(x=>x.section))].sort(); sections.forEach(s=>{const o=document.createElement('option'); o.value=s; o.textContent=s; sel.appendChild(o);});}
function matchingLines(page, query, mode, max){const qn=norm(query); const terms=qn.split(' ').filter(Boolean); const lines=(page.text||'').split('\n'); let out=[]; for(const line of lines){const ln=norm(line); let ok=false; if(mode==='all'||mode==='persona') ok=terms.every(t=>ln.includes(t)); else if(mode==='any') ok=terms.some(t=>ln.includes(t)); else ok=ln.includes(qn); if(ok) out.push(line); if(out.length>=max) break;} return out;}
function pageMatches(page, query, mode){const qn=norm(query); if(!qn) return false; const txt=norm(page.text); const terms=qn.split(' ').filter(Boolean); if(mode==='all'||mode==='persona') return terms.every(t=>txt.includes(t)); if(mode==='any') return terms.some(t=>txt.includes(t)); if(mode==='expediente'){ const compact=s=>norm(s).replace(/\s+/g,'').replace(/-/g,''); const cq=compact(query); return compact(page.text).includes(cq) || (page.expedientes_detectados||[]).some(e=>compact(e).includes(cq)); } return txt.includes(qn);}
function logSearch(q, mode, count){const logs=JSON.parse(localStorage.getItem('cj_logs')||'[]'); logs.unshift({fecha:new Date().toLocaleString('es-MX'), q, mode, count}); localStorage.setItem('cj_logs',JSON.stringify(logs.slice(0,100)));}
function runSearch(){const q=$('#q')?.value||''; const mode=$('#mode')?.value||'exact'; const section=$('#sectionFilter')?.value||''; const max=parseInt($('#snippetLimit')?.value||'5',10); const results=data().filter(p=>(!section||p.section===section)&&pageMatches(p,q,mode)).map(p=>({...p,snippets:matchingLines(p,q,mode,max)})); lastResults=results; renderResults(results,q,mode); logSearch(q,mode,results.length); renderTimeline(results); renderReport();}
function renderMetrics(results){const m=$('#metrics'); if(!m) return; const exps=new Set(); results.forEach(r=>(r.expedientes_detectados||[]).forEach(e=>exps.add(e))); const sections=new Set(results.map(r=>r.section)); const html=[['Páginas con coincidencia',results.length],['Expedientes detectados',exps.size],['Secciones relacionadas',sections.size],['Total de páginas indexadas',data().length]].map(([a,b])=>`<div class="metric"><strong>${b}</strong><span>${a}</span></div>`).join(''); m.innerHTML=html;}
function renderResults(results,q,mode){renderMetrics(results); const c=$('#resultCount'); if(c) c.textContent=`${results.length} resultado${results.length===1?'':'s'}`; const box=$('#results'); if(!box) return; box.textContent=''; if(!q.trim()){box.innerHTML='<p class="hint">Ingrese un término de búsqueda.</p>'; return;} if(!results.length){box.innerHTML='<p class="warning wide">No se encontraron coincidencias literales en el texto extraído del PDF. Revise acentos, variantes de nombre, abreviaturas o pruebe “todos los términos”.</p>'; return;} results.forEach(r=>{const article=document.createElement('article'); article.className='result'; const head=document.createElement('div'); head.className='result-head'; const title=document.createElement('h3'); title.textContent=`Página PDF ${r.page}`+(r.printed_page_estimated?` · página impresa estimada ${r.printed_page_estimated}`:''); const badge=document.createElement('span'); badge.className='badge'; badge.textContent=r.section; head.append(title,badge); article.append(head); const meta=document.createElement('p'); meta.className='meta'; meta.textContent=(r.expedientes_detectados&&r.expedientes_detectados.length)?`Expedientes/referencias detectadas: ${r.expedientes_detectados.slice(0,12).join(', ')}`:'Sin expediente detectado automáticamente en esta página.'; article.append(meta); const ul=document.createElement('ul'); ul.className='snippets'; const snips=r.snippets.length?r.snippets:[(r.text||'').slice(0,500)]; snips.forEach(s=>{const li=document.createElement('li'); li.textContent=s; ul.append(li);}); article.append(ul); const a=document.createElement('a'); a.className='secondary'; a.href=`${PDF_URL}#page=${r.page}`; a.target='_blank'; a.rel='noopener noreferrer'; a.textContent='Abrir PDF en esta página'; article.append(a); box.append(article);});}
function exportCsv(){if(!lastResults.length){alert('No hay resultados para exportar.'); return;} const rows=[['pagina_pdf','pagina_impresa_estimada','seccion','expedientes_detectados','lineas_coincidentes','pdf_url']]; lastResults.forEach(r=>rows.push([r.page,r.printed_page_estimated||'',r.section,(r.expedientes_detectados||[]).join(' | '),(r.snippets||[]).join(' || '),`${PDF_URL}#page=${r.page}`])); const csv=rows.map(row=>row.map(escCsv).join(',')).join('\n'); const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download='consulta_judicial_resultados.csv'; a.click(); URL.revokeObjectURL(url);}
function setupSearch(){if(!$('#searchBtn')) return; populateSections(); $('#searchBtn').addEventListener('click',runSearch); $('#q').addEventListener('keydown',e=>{if(e.key==='Enter') runSearch();}); $('#clearBtn')?.addEventListener('click',()=>{ $('#q').value=''; lastResults=[]; renderResults([],'','exact'); }); $('#csvBtn')?.addEventListener('click',exportCsv); const params=new URLSearchParams(location.search); if(params.get('q')){ $('#q').value=params.get('q'); runSearch(); }}
function renderTimeline(results){const t=$('#timeline'); if(!t) return; t.textContent=''; (results||lastResults).forEach(r=>{const div=document.createElement('div'); div.className='timeitem'; div.textContent=`31/03/2022 · Página PDF ${r.page} · ${r.section} · ${(r.expedientes_detectados||[]).slice(0,3).join(', ')}`; t.append(div);});}
function renderSectionIndex(){const box=$('#sectionIndex'); if(!box) return; const counts={}; data().forEach(p=>counts[p.section]=(counts[p.section]||0)+1); Object.entries(counts).forEach(([s,n])=>{const c=document.createElement('span'); c.className='chip'; c.textContent=`${s}: ${n} páginas`; box.append(c);});}
function renderReport(){const m=$('#reportMetrics'); if(m){const total=data().length; const sections=new Set(data().map(p=>p.section)).size; const expCount=data().reduce((a,p)=>a+(p.expedientes_detectados||[]).length,0); m.innerHTML=[['Páginas indexadas',total],['Secciones',sections],['Referencias tipo expediente',expCount],['Consultas en bitácora',JSON.parse(localStorage.getItem('cj_logs')||'[]').length]].map(([a,b])=>`<div class="metric"><strong>${b}</strong><span>${a}</span></div>`).join('');}
 const bars=$('#bars'); if(bars){const counts={}; data().forEach(p=>counts[p.section]=(counts[p.section]||0)+1); const max=Math.max(...Object.values(counts)); bars.innerHTML=Object.entries(counts).map(([s,n])=>`<div class="bar"><span>${s}</span><span><i style="width:${Math.round(n/max*100)}%"></i></span><b>${n}</b></div>`).join('');}
 renderLogs();}
function renderLogs(){const box=$('#logTable'); if(!box) return; const logs=JSON.parse(localStorage.getItem('cj_logs')||'[]'); if(!logs.length){box.innerHTML='<p class="hint">Aún no hay consultas registradas en este navegador.</p>'; return;} box.innerHTML='<table><thead><tr><th>Fecha</th><th>Búsqueda</th><th>Modo</th><th>Resultados</th></tr></thead><tbody>'+logs.map(l=>`<tr><td>${l.fecha}</td><td>${l.q}</td><td>${l.mode}</td><td>${l.count}</td></tr>`).join('')+'</tbody></table>';}
function homeCounts(){const e=$('#totalPages'); if(e) e.textContent=data().length; const a=$('#adminPages'); if(a) a.textContent=data().length;}
requireSession(); setupLogin(); setupLogout(); setupSearch(); renderSectionIndex(); renderReport(); homeCounts();
})();
